"""Export the local corpus to a JSON fixture, or seed a DB from one.

The pipeline's working data lives under ``data/`` and is gitignored: the
raw API dumps, the SQLite DB and the vector index are all regenerated by
``run_pipeline.py`` + ``run_index.py``. That is the right call for a
dataset — except that CI has no Hacker News access, so it cannot rebuild
the corpus before running the retrieval eval.

So the cleaned posts (text only — no embeddings) are checked in as
``tests/fixtures/ci_corpus.json``. Seeding rebuilds a full DB *and*
vector index from them with the same local model the pipeline uses, so
CI reproduces the real retrieval numbers with zero network.

Embeddings are deliberately not stored in the fixture: re-embedding every
post on seed means the fixture doubles as a regression test for the
embedder (same texts + same model => same index).

Usage:
    python run_corpus.py export                  # DB -> tests/fixtures/ci_corpus.json
    python run_corpus.py export my_corpus.json   # DB -> another file
    python run_corpus.py seed                    # fixture -> data/market_intel.db + index
    python run_corpus.py seed --db /tmp/eval.db  # seed somewhere else

``seed`` is idempotent (INSERT OR IGNORE) but always rebuilds the index,
so re-running it is safe.
"""

import argparse
import json
import sqlite3
import sys
from pathlib import Path

from market_intel import vector
from market_intel.store import connect, insert_posts

# Exactly the fields store.insert_posts reads. ``fetched_at`` is stamped
# at insert time, so it is intentionally not part of the fixture.
FIELDS = [
    "id", "competitor", "source", "community", "title", "body", "url",
    "author", "created_utc", "score", "num_comments",
]

DEFAULT_FIXTURE = "tests/fixtures/ci_corpus.json"
DEFAULT_DB = "data/market_intel.db"


def export(fixture_path: str, db_path: str) -> int:
    """Write the posts in ``db_path`` to ``fixture_path`` as JSON."""
    conn = connect(db_path)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        f"SELECT {', '.join(FIELDS)} FROM posts ORDER BY id"
    ).fetchall()
    conn.close()

    records = [{k: r[k] for k in FIELDS} for r in rows]
    out = Path(fixture_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(records, indent=1, ensure_ascii=False),
                   encoding="utf-8")

    print(f"  exported: {len(records)} posts -> {out}")
    print(f"  bytes   : {out.stat().st_size}")
    return len(records)


def load_fixture(fixture_path: str) -> list[dict]:
    with open(fixture_path, encoding="utf-8") as f:
        records = json.load(f)
    if not isinstance(records, list) or not records:
        raise SystemExit(f"{fixture_path}: expected a non-empty JSON list")
    missing = [f for f in ("id", "competitor", "title") if f not in records[0]]
    if missing:
        raise SystemExit(f"{fixture_path}: records are missing {missing}")
    return records


def seed(fixture_path: str, db_path: str) -> int:
    """Rebuild a DB + vector index from the fixture. Returns chunk count."""
    records = load_fixture(fixture_path)
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)

    conn = connect(db_path)
    inserted = insert_posts(conn, records)
    chunks = vector.build_index(conn, verbose=False)
    stored = conn.execute("SELECT COUNT(*) FROM posts").fetchone()[0]
    conn.close()

    print(f"  fixture : {len(records)} posts from {fixture_path}")
    print(f"  stored  : {inserted} new rows ({stored} total)")
    print(f"  index   : {chunks} chunks")
    print(f"  db      : {db_path}")
    return chunks


def main(action: str, path: str | None, db: str) -> None:
    if action == "export":
        export(path or DEFAULT_FIXTURE, db)
    else:
        seed(path or DEFAULT_FIXTURE, db)


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["export", "seed"],
                        help="export the local DB to a fixture, or seed a DB from one")
    parser.add_argument("path", nargs="?", default=None,
                        help=f"fixture file (default: {DEFAULT_FIXTURE})")
    parser.add_argument("--db", default=DEFAULT_DB,
                        help=f"SQLite DB path (default: {DEFAULT_DB})")
    args = parser.parse_args()
    main(args.action, args.path, args.db)
